
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookLove.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {

        this.Basket = new HashSet<Basket>();

        this.GuestBasket = new HashSet<GuestBasket>();

        this.OrderDetail = new HashSet<OrderDetail>();

        this.Supple = new HashSet<Supple>();

    }


    public int id { get; set; }

    public string title { get; set; }

    public int idAuthor { get; set; }

    public int idGenre { get; set; }

    public int idPublisher { get; set; }

    public int count { get; set; }

    public double price { get; set; }

    public string pucture { get; set; }



    public virtual Author Author { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Basket> Basket { get; set; }

    public virtual Genre Genre { get; set; }

    public virtual Publisher Publisher { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GuestBasket> GuestBasket { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Supple> Supple { get; set; }

}

}
