
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookLove.Model
{

    using System;
    using System.Collections.Generic;

    public partial class Order
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {

            this.GuestBasket = new HashSet<GuestBasket>();

            this.OrderDetail = new HashSet<OrderDetail>();

        }


        public int id { get; set; }

        public int idUser { get; set; }

        public System.DateTime orderDate { get; set; }

        public int statusId { get; set; }

        public string address { get; set; }

        public double totalPrice { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<GuestBasket> GuestBasket { get; set; }

        public virtual OrderStatus OrderStatus { get; set; }

        public virtual Registration Registration { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }

        public string OrderSummary => $"Заказ №{id} - {orderDate.ToShortDateString()}";
    }

}
