
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BookLove.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Supple
{

    public int id { get; set; }

    public int idProvider { get; set; }

    public int idBook { get; set; }

    public int idClient { get; set; }

    public System.DateTime dateSupple { get; set; }

    public string description { get; set; }

    public double totalPrice { get; set; }

    public int count { get; set; }



    public virtual Book Book { get; set; }

    public virtual Client Client { get; set; }

    public virtual Provider Provider { get; set; }

}

}
